"""
Integration tests for the full train → evaluate pipeline.

Tests the end-to-end workflow including:
- Data loading and processing
- Model training
- Model evaluation
- Artifact generation
"""

import pytest
import torch
import numpy as np
import os
import tempfile

pytestmark = pytest.mark.integration
import shutil
from pathlib import Path

from tsgen.train import train_model
from tsgen.evaluate import evaluate_model
from tsgen.evaluation import EvaluationResult
from tsgen.data.processor import LogReturnProcessor
from tsgen.models.registry import ModelRegistry
from tsgen.config.schema import ExperimentConfig
from tsgen.tracking.base import NoOpTracker, FileTracker


@pytest.fixture
def temp_dir():
    """Create a temporary directory for test artifacts."""
    temp_path = tempfile.mkdtemp()
    yield temp_path
    # Cleanup
    shutil.rmtree(temp_path, ignore_errors=True)


@pytest.fixture
def minimal_config():
    """Minimal configuration for quick testing."""
    return ExperimentConfig(
        experiment_name='test_integration',
        model_type='unet',
        tracker='noop',
        data={
            'tickers': ['AAPL', 'MSFT'],
            'start_date': '2024-01-01',
            'end_date': '2024-12-31',
            'sequence_length': 64,
        },
        training={
            'batch_size': 16,
            'epochs': 3,  # Just 3 epochs for speed
            'timesteps': 100,  # Fewer timesteps for speed
            'learning_rate': 1e-3,
        },
        model={
            'base_channels': 32,
        },
        data_pipeline=[
            {'load_prices': {'column': 'adj_close'}},
            {'clean_data': {'strategy': 'ffill_drop'}},
            {'process_prices': {'fit': True}},
            {'create_windows': {'sequence_length': 64}},
            {'create_dataloader': {'batch_size': 16, 'shuffle': True}}
        ]
    )


def test_train_pipeline_unet(minimal_config, temp_dir):
    """Test training pipeline with UNet model."""
    # Create tracker with experiment directory
    tracker = FileTracker(experiment_dir=temp_dir)

    # Run training
    model, processor = train_model(minimal_config, tracker)

    # Verify model was created
    assert model is not None
    assert isinstance(model, torch.nn.Module)

    # Verify processor was created
    assert processor is not None

    # Verify artifacts were saved by tracker
    assert os.path.exists(os.path.join(temp_dir, 'artifacts', 'models', 'model_final.pt'))
    assert os.path.exists(os.path.join(temp_dir, 'artifacts', 'data', 'processor.pkl'))


def test_train_pipeline_transformer(minimal_config, temp_dir):
    """Test training pipeline with Transformer model."""
    # Create new config for transformer
    base = minimal_config.to_dict()
    base['model_type'] = 'transformer'
    base['model'] = {'dim': 32, 'depth': 2, 'heads': 2, 'mlp_dim': 64}
    config = ExperimentConfig(**base)

    # Create tracker with experiment directory
    tracker = FileTracker(experiment_dir=temp_dir)

    # Run training
    model, processor = train_model(config, tracker)

    # Verify model was created
    assert model is not None
    assert isinstance(model, torch.nn.Module)

    # Verify artifacts were saved by tracker
    assert os.path.exists(os.path.join(temp_dir, 'artifacts', 'models', 'model_final.pt'))
    assert os.path.exists(os.path.join(temp_dir, 'artifacts', 'data', 'processor.pkl'))


def test_evaluate_pipeline(minimal_config, temp_dir):
    """Test evaluation pipeline after training."""
    # Create tracker with experiment directory
    tracker = FileTracker(experiment_dir=temp_dir)

    # First train a model
    model, processor = train_model(minimal_config, tracker)

    # Now evaluate it with ExperimentConfig directly
    base = minimal_config.to_dict()
    base['evaluation'] = {'num_samples': 100}
    eval_config = ExperimentConfig(**base)

    # Run evaluation
    result = evaluate_model(eval_config, tracker)

    # Verify metrics were computed
    assert result is not None
    assert isinstance(result, EvaluationResult)

    # Check for expected metric keys
    expected_keys = ['discriminator_accuracy']
    for key in expected_keys:
        assert key in result.metrics, f"Expected metric '{key}' not found"

    # Verify plots were generated by tracker
    assert os.path.exists(os.path.join(temp_dir, 'artifacts', 'plots'))


def test_train_eval_end_to_end(minimal_config, temp_dir):
    """Test complete train → evaluate workflow."""
    # Configure for end-to-end test
    base = minimal_config.to_dict()
    base.setdefault('training', {})['epochs'] = 5
    base['evaluation'] = {'num_samples': 50}
    config = ExperimentConfig(**base)

    # Create tracker with experiment directory
    tracker = FileTracker(experiment_dir=temp_dir)

    # Step 1: Train model
    print("\n=== Training ===")
    model, processor = train_model(config, tracker)
    assert model is not None
    assert processor is not None

    # Step 2: Verify training artifacts
    assert os.path.exists(os.path.join(temp_dir, 'artifacts', 'models', 'model_final.pt'))
    assert os.path.exists(os.path.join(temp_dir, 'artifacts', 'data', 'processor.pkl'))

    # Step 3: Evaluate model with ExperimentConfig directly
    print("\n=== Evaluating ===")
    result = evaluate_model(config, tracker)
    assert result is not None

    # Step 4: Verify evaluation produced results
    assert 'discriminator_accuracy' in result.metrics

    # Step 5: Verify plots exist
    plot_dir = Path(temp_dir) / 'artifacts' / 'plots'
    assert plot_dir.exists()

    print(f"\n=== Test Complete ===")
    print(f"Discriminator Accuracy: {result.metrics.get('discriminator_accuracy', 'N/A')}")


def test_data_pipeline_consistency(minimal_config):
    """Test that data pipeline produces consistent results."""
    from tsgen.data.pipeline import load_prices, clean_data

    # Load and clean data using pipeline
    data_cfg = minimal_config.get_data_config()
    data = load_prices(
        data_cfg.tickers,
        data_cfg.start_date,
        data_cfg.end_date
    )
    data = clean_data(data)

    # Verify data shape
    assert data is not None
    assert len(data) > 0
    assert data.shape[1] == len(data_cfg.tickers)

    # Create processor
    processor = LogReturnProcessor()
    processor.fit(data)

    # Transform data (returns numpy array)
    transformed = processor.transform(data)
    assert transformed is not None
    # Transform returns scaled returns (one less row than prices)
    assert len(transformed) == len(data) - 1

    # Inverse transform
    initial_price = data.iloc[0].values
    reconstructed = processor.inverse_transform(transformed, initial_price)

    # Verify shapes - inverse_transform returns (Batch, Seq+1, Feat) 3D array
    # Since we passed 2D input, batch=1
    assert reconstructed.shape == (1, len(data), len(data_cfg.tickers))

    # Verify values are reasonable (positive prices)
    assert np.all(reconstructed > 0)


def test_model_loading_consistency(minimal_config, temp_dir):
    """Test that saved models can be loaded and produce consistent outputs."""
    original_dir = os.getcwd()
    os.chdir(temp_dir)

    try:
        # Create tracker
        tracker = NoOpTracker()

        # Train a model
        model, processor = train_model(minimal_config, tracker)

        # Generate sample output
        data_cfg = minimal_config.get_data_config()
        training_cfg = minimal_config.get_training_config()
        x = torch.randn(2, data_cfg.sequence_length, len(data_cfg.tickers))
        t = torch.randint(0, training_cfg.timesteps, (2,))

        with torch.no_grad():
            output1 = model(x, t)

        # Save model
        torch.save(model.state_dict(), 'test_model.pt')

        # Load model
        loaded_model = ModelRegistry.create(minimal_config)
        loaded_model.load_state_dict(torch.load('test_model.pt', weights_only=True))
        loaded_model.eval()

        # Generate output from loaded model
        with torch.no_grad():
            output2 = loaded_model(x, t)

        # Verify outputs are identical
        assert torch.allclose(output1, output2, atol=1e-6)

    finally:
        os.chdir(original_dir)


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
